### ISSUE TITLE
Uncaught TypeError: tui_date_picker_1.default is not a constructor

### ISSUE THREAD

**Issue by Federico-Luna** [nhn/tui.grid#1960]
First of all, congrats for your effort.

I am starting to use TOAST UI Grid and I am testing it with a very simple example and I have the following problem:

When the focus is placed on the date field, the following error appears:

Uncaught TypeError: tui_date_picker_1.default is not a constructor
     at new DatePickerEditor (utils.js:69:8)
     at EditingLayerComp.createEditor(utils.js:69:8)
     at EditingLayerComp.componentDidUpdate (utils.js:69:8)
     at renderComponent (customEvents.js:502:1)
     at setComponentProps(customEvents.js:372:1)
     at renderComponent (customEvents.js:443:1)
     at class_1.forceUpdate(_safeEvent.js:18:1)
     at class_1.setStateUsingSelector (getTarget.js:18:1)
     at Object.fn (off.js:3:1)
     at callObserver (off.js:74:1)

https://jsfiddle.net/Federico_Moon/5c0sjb64/3/

Thank you

**Comment by mthan0313** [comment]
I am also experiencing the same symptoms.
It is necessary to analyze the cause of the symptom and find a solution.

**Comment by b2vincent** [comment]
Experiencing the same symptoms too. Is it linked to the fact of using through CDN rather than through a build ?
A fallback solution is to use another date editor such as Flatpickr, which is a bit unfortunate.
